# Generated by Django 5.0.3 on 2024-04-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_userprofile_name_alter_userprofile_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday_date',
            field=models.DateTimeField(),
        ),
    ]
