# Generated by Django 5.0.3 on 2024-04-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_userprofile_birthday_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday_date',
            field=models.DateField(),
        ),
    ]
