# Generated by Django 5.0.3 on 2024-04-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=63, null=True)),
                ('surname', models.CharField(blank=True, max_length=63, null=True)),
                ('description', models.TextField(blank=True)),
                ('birthday_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('media', models.FileField(blank=True, null=True, upload_to='profile_media/')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
